# Generated by Django 5.2.7 on 2025-11-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_key_encrypted',
            field=models.TextField(blank=True, help_text='AES-encrypted private key from Node.js', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.CharField(blank=True, help_text="User's Lisk public key", max_length=128, null=True),
        ),
    ]
