# Generated by Django 5.2.7 on 2025-11-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_private_key_encrypted_user_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='private_key_encrypted',
            field=models.TextField(blank=True, help_text='AES-encrypted private key from Node.js', max_length=256, null=True),
        ),
    ]
