Backend service is deployed and running!
No changes detected in app 'forensic_corpus'
# Generated by Django 5.2.11 on 2026-02-14 21:35

import django.contrib.postgres.fields
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalProtocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('issuing_body', models.CharField(max_length=255)),
                ('specialty', models.CharField(choices=[('cardiology', 'Cardiology'), ('oncology', 'Oncology'), ('emergency', 'Emergency Medicine'), ('general', 'General Practice'), ('neurology', 'Neurology'), ('internal_medicine', 'Internal Medicine'), ('family_medicine', 'Family Medicine'), ('pediatrics', 'Pediatrics'), ('obstetrics_gynecology', 'Obstetrics & Gynecology'), ('surgery_general', 'General Surgery'), ('orthopedics', 'Orthopedics'), ('anesthesiology', 'Anesthesiology'), ('critical_care', 'Critical Care'), ('infectious_disease', 'Infectious Disease'), ('pulmonology', 'Pulmonology'), ('nephrology', 'Nephrology'), ('gastroenterology', 'Gastroenterology'), ('endocrinology', 'Endocrinology'), ('hematology', 'Hematology'), ('radiology', 'Radiology'), ('pathology', 'Pathology'), ('psychiatry', 'Psychiatry'), ('dermatology', 'Dermatology'), ('urology', 'Urology'), ('ophthalmology', 'Ophthalmology'), ('otolaryngology', 'Otolaryngology (ENT)'), ('rehabilitation', 'Physical Medicine & Rehabilitation'), ('palliative_care', 'Palliative Care')], max_length=50)),
                ('min_facility_level', models.CharField(choices=[('level_1', 'Community (CHVs)'), ('level_2', 'Dispensaries'), ('level_3', 'Health Centres'), ('level_4', 'Sub-County Hospitals'), ('level_5', 'County Referral Hospitals'), ('level_6', 'National Referral (KNH/MTRH)')], default='level_2', max_length=20)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForensicRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(db_index=True, max_length=50)),
                ('rule_type', models.CharField(choices=[('temporal', 'Temporal Sequence'), ('existence', 'Evidence Requirement'), ('threshold', 'Vital/Lab Threshold'), ('contra', 'Contraindication'), ('exclusive', 'Mutually Exclusive'), ('duplicate', 'Duplicate Event Detection'), ('conditional_existence', 'Conditional Evidence Requirement'), ('protocol_validity', 'Protocol Time Applicability'), ('count_sanity', 'Event Count Sanity'), ('monotonic', 'Monotonic Event Ordering')], max_length=50)),
                ('text_description', models.TextField()),
                ('logic_config', models.JSONField(default=dict)),
                ('applicable_facility_levels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('level_1', 'Community (CHVs)'), ('level_2', 'Dispensaries'), ('level_3', 'Health Centres'), ('level_4', 'Sub-County Hospitals'), ('level_5', 'County Referral Hospitals'), ('level_6', 'National Referral (KNH/MTRH)')], max_length=20), default=list, help_text='Facility levels where this specific rule is enforceable.', size=None)),
                ('scope_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('clinical', 'Clinical (Patient Care)'), ('facility', 'Facility (Operations/Admin)'), ('billing', 'Billing & Coding'), ('legal', 'Legal & Regulatory')], max_length=50), default=list, help_text="Deterministic enforcement contexts (e.g., ['clinical'])", size=None)),
                ('intent_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('safety', 'Patient Safety'), ('quality', 'Quality of Care'), ('compliance', 'Regulatory Compliance'), ('billing', 'Billing Integrity'), ('documentation', 'Documentation Sufficiency')], max_length=50), default=list, help_text="Why this rule exists (e.g., ['safety', 'compliance'])", size=None)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='forensic_corpus.clinicalprotocol')),
            ],
        ),
        migrations.CreateModel(
            name='RuleEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector', pgvector.django.vector.VectorField(dimensions=768)),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='forensic_corpus.forensicrule')),
            ],
        ),
    ]
