Backend service is deployed and running!
No changes detected in app 'forensic_agent'
# Generated by Django 5.2.11 on 2026-02-14 21:34

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.CharField(max_length=100)),
                ('claim_payload', models.JSONField(help_text='The raw claim data received')),
                ('query_intent', models.TextField(help_text='The clinical query/scenario')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Processing'), ('CLEARED', 'Cleared (Valid)'), ('HALTED', 'Halted (Invalid)'), ('ERROR', 'System Error')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verdict_json', models.JSONField(blank=True, help_text='Structured gate findings', null=True)),
                ('retrieved_protocols', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('final_report', models.JSONField(blank=True, help_text='MedGemma output or Refusal notice', null=True)),
                ('agent_trace', models.JSONField(blank=True, default=list, help_text='Execution Log')),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_channel', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
